worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        # ---- MICROSERVICIO PYTHON (Elías) ----
        # Elías configuró dos grupos de rutas: /auth y /api/usuarios
        location /auth/ {
            proxy_pass http://usuarios-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/usuarios/ {
            proxy_pass http://usuarios-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /api/tutores/ {
            proxy_pass http://usuarios-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---- MICROSERVICIO JAVA (Nicolás) ----
        # Nicolás configuró explícitamente @RequestMapping("/api/reservas")
        location /api/reservas/ {
            proxy_pass http://reservas-service:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---- MICROSERVICIO NODE.JS (Laura) ----
        # Laura configuró app.use('/api/materias', ...) y app.use('/api/bloques', ...)
        location /api/materias/ {
            proxy_pass http://catalogo-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/bloques/ {
            proxy_pass http://catalogo-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 404 "API Gateway Tutorias - Endpoint no encontrado";
        }
    }
}